### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

### ISSUE THREAD

**Issue by datomnurdin** [googlesamples/tango-examples-unity#12]
I try to run the sample project via Android then I got this error message

```
05-29 06:09:58.637: E/AndroidRuntime(2116): FATAL EXCEPTION: main
05-29 06:09:58.637: E/AndroidRuntime(2116): Process: com.projecttango.experiments.unitymotiontracking, PID: 2116
05-29 06:09:58.637: E/AndroidRuntime(2116): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.projecttango.experiments.unitymotiontracking/com.google.unity.GoogleUnityActivity}: java.lang.ClassNotFoundException: Didn't find class "com.google.unity.GoogleUnityActivity" on path: DexPathList[[zip file "/data/app/com.projecttango.experiments.unitymotiontracking-1/base.apk"],nativeLibraryDirectories=[/data/app/com.projecttango.experiments.unitymotiontracking-1/lib/x86, /vendor/lib, /system/lib]]
05-29 06:09:58.637: E/AndroidRuntime(2116):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2236)
05-29 06:09:58.637: E/AndroidRuntime(2116):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
05-29 06:09:58.637: E/AndroidRuntime(2116):     at android.app.ActivityThread.access$800(ActivityThread.java:151)
05-29 06:09:58.637: E/AndroidRuntime(2116):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
05-29 06:09:58.637: E/AndroidRuntime(2116):     at android.os.Handler.dispatchMessage(Handler.java:102)
05-29 06:09:58.637: E/AndroidRuntime(2116):     at android.os.Looper.loop(Looper.java:135)
05-29 06:09:58.637: E/AndroidRuntime(2116):     at android.app.ActivityThread.main(ActivityThread.java:5254)
05-29 06:09:58.637: E/AndroidRuntime(2116):     at java.lang.reflect.Method.invoke(Native Method)
05-29 06:09:58.637: E/AndroidRuntime(2116):     at java.lang.reflect.Method.invoke(Method.java:372)
05-29 06:09:58.637: E/AndroidRuntime(2116):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
05-29 06:09:58.637: E/AndroidRuntime(2116):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
05-29 06:09:58.637: E/AndroidRuntime(2116): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.unity.GoogleUnityActivity" on path: DexPathList[[zip file "/data/app/com.projecttango.experiments.unitymotiontracking-1/base.apk"],nativeLibraryDirectories=[/data/app/com.projecttango.experiments.unitymotiontracking-1/lib/x86, /vendor/lib, /system/lib]]
05-29 06:09:58.637: E/AndroidRuntime(2116):     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-29 06:09:58.637: E/AndroidRuntime(2116):     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
05-29 06:09:58.637: E/AndroidRuntime(2116):     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
05-29 06:09:58.637: E/AndroidRuntime(2116):     at android.app.Instrumentation.newActivity(Instrumentation.java:1066)
05-29 06:09:58.637: E/AndroidRuntime(2116):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2226)
05-29 06:09:58.637: E/AndroidRuntime(2116):     ... 10 more
05-29 06:09:58.637: E/AndroidRuntime(2116):     Suppressed: java.lang.ClassNotFoundException: com.google.unity.GoogleUnityActivity
05-29 06:09:58.637: E/AndroidRuntime(2116):         at java.lang.Class.classForName(Native Method)
05-29 06:09:58.637: E/AndroidRuntime(2116):         at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
05-29 06:09:58.637: E/AndroidRuntime(2116):         at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
05-29 06:09:58.637: E/AndroidRuntime(2116):         at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
05-29 06:09:58.637: E/AndroidRuntime(2116):         ... 13 more
05-29 06:09:58.637: E/AndroidRuntime(2116):     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

What I'm missing here? I didn't touch any codes inside it.

**Comment by jguomoto** [comment]
@datomnurdin Based on your previous issue report, I just want to double check that if you received this error message by compiling it through unity and pushed on a Tango device?

**Comment by datomnurdin** [comment]
I'm using on normal device, not Tango device. Thank you for your replied.
