### ISSUE TITLE
Unity 5.4 and google-unity-wrapper crashes

### ISSUE THREAD

**Issue by nickersonr** [googlesamples/tango-examples-unity#55]
On the new version of unity 5.4.0, using the google unity activity causes a crash with the error of "Unity Android Application “Unable to load native library”"

**Comment by imwithye** [comment]
We are using 5.4.2 and it crashes too. This is the logcat

```
W/ActivityManager(  908):   Force finishing activity com.projecttango.unityexamples/com.google.unity.GoogleUnityActivity
W/st-log  ( 1776): Initial features: Max - 8893, Min - 9039
W/InputDispatcher(  908): channel '653057c0 com.projecttango.unityexamples/com.google.unity.GoogleUnityActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  908): channel '653057c0 com.projecttango.unityexamples/com.google.unity.GoogleUnityActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
D/phs:ipc-loc(  182): Socket 17: hangup from client "com.projecttango.unityexamples"
E/JavaBinder(  908): !!! FAILED BINDER TRANSACTION !!!
W/ActivityManager(  908): Exception thrown during pause
W/ActivityManager(  908): android.os.TransactionTooLargeException
W/ActivityManager(  908):       at android.os.BinderProxy.transact(Native Method)
W/ActivityManager(  908):       at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:660)
W/ActivityManager(  908):       at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:768)
W/ActivityManager(  908):       at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2473)
W/ActivityManager(  908):       at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2347)
W/ActivityManager(  908):       at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2045)
W/ActivityManager(  908):       at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:9569)
W/ActivityManager(  908):       at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:9462)
W/ActivityManager(  908):       at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:10107)
W/ActivityManager(  908):       at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:9658)
W/ActivityManager(  908):       at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
```

**Comment by vikassharma27** [comment]
Please Remove Oculus option from Other Settings -> Virtual Reality SDSs  and set None option there

![screen shot 2016-11-21 at 12 29 49 pm](https://cloud.githubusercontent.com/assets/9077180/20473377/3cbafe2c-afe6-11e6-8a22-34783396135d.png)

**Comment by chaosemer** [comment]
Is this still an issue for you? We've addressed similar issues over the past few months but neglected to update the GitHub issues.

**Comment by chaosemer** [comment]
Seems like the issue is solved. Please reopen if this is still an issue for you.

**Comment by Saraceni** [comment]
I am having the exact same problem. I have removed the oculus option from the SKDs and left only the None option. It still crashes with this same error. I have deleted and reimported the Plugin but it didn't worked either.

**Comment by chaosemer** [comment]
@Saraceni, can you please open a new issue and provide a full logcat? That'll help us diagnose this.

Thank you!

**Comment by Mahalakshmi269** [comment]
Even i am having the same problem

**Comment by Salma175** [comment]
even i am having the same issue

**Comment by chaosemer** [comment]
@Salma175, could you please open a new issue and provide a full logcat? That'll help us diagnose this.

Thank you!
